/* Automatically generated by './build/bin/build-entry.js' */


import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
,
  CollapseTransition
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  CollapseTransition,

};
